name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9', '3.10']
    env:
      LATERALITY_DEV_MODE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Using Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing Dependencies and Project [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install -e .
      - name: Running Test Suite [pytest]
        run: |
          pytest . --cache-clear
