name: mypy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: 'Using Python 3.9'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installation
        run: |
          python -m pip install pip --upgrade pip
          pip install -e .[tests]
      - name: Type Checking
        run: |
          mypy src/nerb
